name: Upload to Cloudflare R2

on:
  workflow_dispatch:

jobs:
  Prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # TODO: Replace with your own script to generate static assets
      - name: Generate files with timestamps
        run: |
          mkdir -p some-files
          echo "foo - $(date '+%Y-%m-%d %H:%M:%S')" > some-files/foo.txt
          echo "bar - $(date '+%Y-%m-%d %H:%M:%S')" > some-files/bar.txt
          echo "baz - $(date '+%Y-%m-%d %H:%M:%S')" > some-files/baz.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: prepared-files
          path: some-files/

  Upload:
    runs-on: ubuntu-latest
    needs: Prepare # run the Prepare job first
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      R2_BUCKET_NAME: ${{ secrets.R2_BUCKET_NAME }}
      R2_ENDPOINT_URL: ${{ secrets.R2_ENDPOINT_URL }}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: prepared-files # from the `Prepare` job
          path: some-files # where to download the artifact

      - name: Setup uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.4.x"

      - name: Upload files to Cloudflare R2
        run: |
          uv run --with awscli aws s3 cp ./some-files "s3://${R2_BUCKET_NAME}/" \
            --recursive \
            --endpoint-url "${R2_ENDPOINT_URL}"
